name: apiverve_imagetotext
description: Image to Text is a simple tool for extracting text from images. It returns the extracted text.
version: 1.1.14
homepage: https://imagetotext.apiverve.com?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/imagetotext-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
